version: '3'
services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
       - "5430:5432"
    volumes:
      - ./postgres-install-extensions.sh:/docker-entrypoint-initdb.d/postgres-install-extensions.sh

#  redis:
#    image: redis
#    ports:
#      - "6379:6379"