# Generated by Django 4.1.3 on 2022-11-12 17:47

import core.utils.path_constructors
import core.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StickerPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('CLIENT', 'Client'), ('OPERATOR', 'Operator')], max_length=10, verbose_name='Role')),
            ],
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.utils.path_constructors.path_to_widget, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg']), core.validators.image_size_validator])),
            ],
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_sticker', models.ImageField(blank=True, null=True, upload_to=core.utils.path_constructors.path_to_sticker, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg']), core.validators.image_size_validator])),
                ('sticker_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stickerpack')),
            ],
        ),
    ]
